pub struct FilePreset {
    pub key: &'static str,
    pub extensions: &'static [&'static str],
}

pub const FILE_PRESETS: &[FilePreset] = &[
    FilePreset {
        key: "media",
        extensions: &["webm", "mp4", "mkv", "avi", "mov"],
    },
    FilePreset {
        key: "audio",
        extensions: &["mp3", "wav", "ogg", "flac"],
    },
    FilePreset {
        key: "images",
        extensions: &["jpg", "jpeg", "png", "gif", "webp", "svg"],
    },
    FilePreset {
        key: "archives",
        extensions: &["zip", "rar", "tar", "gz", "7z"],
    },
    FilePreset {
        key: "documents",
        extensions: &["pdf", "txt", "json", "xml", "csv"],
    },
    FilePreset {
        key: "web",
        extensions: &["php", "html", "js", "env", "config"],
    },
];

pub const SUBDOMAINS: &[&str] = &[
    "www",
    "mail",
    "webmail",
    "smtp",
    "pop",
    "imap",
    "mx",
    "email",
    "admin",
    "administrator",
    "api",
    "api-v1",
    "api-v2",
    "app",
    "apps",
    "auth",
    "login",
    "signin",
    "sso",
    "oauth",
    "dev",
    "development",
    "test",
    "testing",
    "stage",
    "staging",
    "qa",
    "uat",
    "demo",
    "sandbox",
    "prod",
    "production",
    "portal",
    "dashboard",
    "console",
    "panel",
    "cpanel",
    "whm",
    "status",
    "health",
    "monitor",
    "metrics",
    "grafana",
    "prometheus",
    "kibana",
    "logs",
    "log",
    "cdn",
    "static",
    "assets",
    "img",
    "images",
    "media",
    "video",
    "videos",
    "download",
    "downloads",
    "files",
    "file",
    "docs",
    "doc",
    "documentation",
    "help",
    "support",
    "kb",
    "wiki",
    "blog",
    "news",
    "shop",
    "store",
    "cart",
    "checkout",
    "billing",
    "payments",
    "pay",
    "secure",
    "vpn",
    "remote",
    "rdp",
    "ssh",
    "ftp",
    "sftp",
    "git",
    "gitlab",
    "github",
    "bitbucket",
    "jenkins",
    "ci",
    "build",
    "deploy",
    "registry",
    "docker",
    "k8s",
    "kubernetes",
    "cloud",
    "aws",
    "azure",
    "gcp",
    "db",
    "database",
    "mysql",
    "postgres",
    "redis",
    "cache",
    "search",
    "elastic",
    "solr",
    "ldap",
    "ad",
    "intranet",
    "internal",
    "private",
    "public",
    "edge",
    "origin",
    "proxy",
    "lb",
    "loadbalancer",
    "ns1",
    "ns2",
    "dns",
    "m",
    "mobile",
    "beta",
    "alpha",
    "old",
    "new",
    "legacy",
    "backup",
    "bak",
    "archive",
    "devops",
    "ops",
    "noc",
    "crm",
    "erp",
    "hr",
    "finance",
    "accounts",
    "account",
    "id",
    "identity",
    "partners",
    "partner",
    "vendors",
    "vendor",
    "events",
    "calendar",
    "chat",
    "meet",
    "teams",
    "voice",
];

pub const FILE_PATHS: &[&str] = &[
    "robots.txt",
    "sitemap.xml",
    "humans.txt",
    "security.txt",
    "favicon.ico",
    "manifest.json",
    ".env",
    ".env.local",
    ".env.production",
    ".git/config",
    ".svn/entries",
    "config.php",
    "config.json",
    "config.xml",
    "settings.php",
    "settings.json",
    "web.config",
    "app.config",
    "backup.{ext}",
    "backups/backup.{ext}",
    "db.{ext}",
    "database.{ext}",
    "dump.{ext}",
    "sql/dump.{ext}",
    "uploads/file.{ext}",
    "uploads/document.{ext}",
    "uploads/image.{ext}",
    "files/file.{ext}",
    "files/archive.{ext}",
    "downloads/archive.{ext}",
    "download/file.{ext}",
    "assets/app.{ext}",
    "assets/main.{ext}",
    "assets/index.{ext}",
    "static/app.{ext}",
    "static/main.{ext}",
    "static/site.{ext}",
    "public/app.{ext}",
    "public/main.{ext}",
    "media/video.{ext}",
    "media/audio.{ext}",
    "media/file.{ext}",
    "images/logo.{ext}",
    "images/banner.{ext}",
    "img/logo.{ext}",
    "img/header.{ext}",
    "documents/report.{ext}",
    "docs/manual.{ext}",
    "docs/api.{ext}",
    "reports/export.{ext}",
    "exports/data.{ext}",
    "data/export.{ext}",
    "api/export.{ext}",
    "admin/export.{ext}",
    "admin/config.{ext}",
    "admin/login.{ext}",
    "login.{ext}",
    "index.{ext}",
    "home.{ext}",
    "about.{ext}",
    "contact.{ext}",
    "privacy.{ext}",
    "terms.{ext}",
    "readme.{ext}",
    "README.{ext}",
    "CHANGELOG.{ext}",
    "LICENSE.{ext}",
    "package.json",
    "composer.json",
    "yarn.lock",
    "package-lock.json",
    "pnpm-lock.yaml",
    "webpack.config.js",
    "vite.config.js",
    "server-status",
    "phpinfo.php",
    "info.php",
    "test.php",
    "debug.php",
    "adminer.php",
    "wp-config.php",
    "wp-content/uploads/file.{ext}",
    "wp-content/uploads/image.{ext}",
    "wp-content/debug.log",
    "storage/logs/laravel.log",
    "var/log/app.log",
    "logs/app.log",
    "tmp/file.{ext}",
    "temp/file.{ext}",
    "old/index.{ext}",
    "backup/index.{ext}",
    "archive/index.{ext}",
    "private/file.{ext}",
    "secret/file.{ext}",
    "uploads/backup.{ext}",
];

pub const MEDIA_DIRECTORIES: &[&str] = &[
    "clips",
    "clip",
    "media",
    "videos",
    "video",
    "assets",
    "static",
    "public",
    "uploads",
    "files",
    "downloads",
];
